version: '3.8'

services:
  web_image_api:
    restart: on-failure
    build: .
    command:
       python main.py
    container_name: tg_chat_bot
    volumes:
      - .:/usr/src/tg_chat_bot
    ports:
      - "8000:8000"
    networks:
      - app_network

  db:
    image: postgres:14-alpine
    container_name: postgres_db_tg_chat_bot
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - app_network
networks:
  app_network:
    driver: bridge